name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: .NET Core CLI
      uses: baruchiro/github-actions@0.0.1
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: unit test
      run: dotnet test
